/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fritz_dmtxdecode_ShowActivity */

#ifndef _Included_com_example_fritz_dmtxdecode_ShowActivity
#define _Included_com_example_fritz_dmtxdecode_ShowActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_fritz_dmtxdecode_ShowActivity_SEARCH_TIMEOUT
#define com_example_fritz_dmtxdecode_ShowActivity_SEARCH_TIMEOUT 10000L
/*
 * Class:     com_example_fritz_dmtxdecode_ShowActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_fritz_dmtxdecode_ShowActivity_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
